export const Questions = [
    {
        prompt:"what is 2 + 2",
        optionA:"5",
        optionB:"4",
        optionC:"3",
        optionD:"2",
        answer:"B",
    },
    {
        prompt:"what is 5 + 2",
        optionA:"5",
        optionB:"4",
        optionC:"3",
        optionD:"7",
        answer:"D",
    },
    {
        prompt:"what is 8 * 5",
        optionA:"50",
        optionB:"40",
        optionC:"30",
        optionD:"20",
        answer:"B",
    },
    {
        prompt:"what is 20 + 2",
        optionA:"25",
        optionB:"24",
        optionC:"23",
        optionD:"22",
        answer:"D",
    },
    {
        prompt:"what is 8 - 5",
        optionA:"5",
        optionB:"4",
        optionC:"3",
        optionD:"2",
        answer:"C",
    },
    {
        prompt:"what is 10 / 2",
        optionA:"5",
        optionB:"4",
        optionC:"3",
        optionD:"2",
        answer:"A",
    },
    {
        prompt:"what is 2 * 2",
        optionA:"5",
        optionB:"4",
        optionC:"3",
        optionD:"2",
        answer:"B",
    },
]